// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAttentionKind } from "./ThreadAttentionKind";

export type ThreadAttentionEvent = { version: number, eventId: string, kind: ThreadAttentionKind, sourceClass: string, sourceRef: string, reference?: string, };
