// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clear the thread's effective context back to fresh initial context. Accepted only while the
 * thread is idle; the rollout keeps every earlier item. Success arrives as
 * `thread/context/cleared`, refusal as an error notification with `contextClearFailed`.
 */
export type ThreadContextClearParams = { threadId: string, };
