// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional, caller-authored guidance for one compaction.
 *
 * An empty value preserves the ordinary compaction path. These controls affect
 * only the working history supplied to the compactor; they do not rewrite the
 * source transcript.
 */
export type CompactionInput = {
/**
 * Additional instructions for what the compacted context should preserve,
 * summarize, or otherwise emphasize.
 */
instructions?: string,
/**
 * Omit inline image bodies from the compactor input and installed compacted
 * history. The original transcript remains unchanged.
 */
discardImages?: boolean,
/**
 * After a successful compaction, allow the next model request to try the
 * Responses WebSocket transport again. A failed attempt returns the session
 * to sticky HTTP fallback; this does not enable automatic retries.
 */
retryWebsocket?: boolean, };
